name: Verbasic
favicon: null
layout_spectrum: 0.8262566355988383
typography_spectrum: 0.052402082132175565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7114872015081346
  lightness: 0.01320115220732987
  saturation: 0.3810219024308026
  rhythmicContrast: 0.2352845270652324
purpose: []
