name: Verbasic
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Welcome to Verbasic!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1875
  lightness: 0.01320115220732987
  saturation: 0.0625
  rhythmicContrast: 0.2352845270652324
purpose: []
